{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baimsg.chat",
    "module": "bytecode-fog",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "bytecode-fog-1.0.0.jar",
          "url": "bytecode-fog-1.0.0.jar",
          "size": 7439,
          "sha512": "68b14c87c540bfc3717633b75b3cc3ce8501ecdeaec554e69593ae7814f4f8b6815408fa0a79491957a2fea7be67b37248d8c44caa2b29a4cc294cab2fe5d2e6",
          "sha256": "92bddbb733f856ca33d90d42bb5fed968047f129729799b4dfc9f65afcbf3e1f",
          "sha1": "ce22cde7b8d4819b66bd532f2280dece158d2f1e",
          "md5": "f5ef4fb6d0731deac98ef655a6f15f48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-all",
          "version": {
            "requires": "6.0_BETA"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "bytecode-fog-1.0.0.jar",
          "url": "bytecode-fog-1.0.0.jar",
          "size": 7439,
          "sha512": "68b14c87c540bfc3717633b75b3cc3ce8501ecdeaec554e69593ae7814f4f8b6815408fa0a79491957a2fea7be67b37248d8c44caa2b29a4cc294cab2fe5d2e6",
          "sha256": "92bddbb733f856ca33d90d42bb5fed968047f129729799b4dfc9f65afcbf3e1f",
          "sha1": "ce22cde7b8d4819b66bd532f2280dece158d2f1e",
          "md5": "f5ef4fb6d0731deac98ef655a6f15f48"
        }
      ]
    }
  ]
}
