{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baimsg.chat",
    "module": "bytecode-fog",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "bytecode-fog-1.0.0.jar",
          "url": "bytecode-fog-1.0.0.jar",
          "size": 45027,
          "sha512": "4b641d5128bf00a8365812138202fe98e561d5a730a3b27c8f7126fb6998d50f8122b95386d37d0ae0dbbbc8fe283064a526fe6b2a9ad9d5c2645bd41d359b2b",
          "sha256": "f4778ab021b98dba914c0175e33cc32331d0ae5dc859df250cddef1823e8986e",
          "sha1": "c508f0c7ab06367345f0b33ed4615a8765401e44",
          "md5": "f0b87f6055ee14b9d0b93a6190367409"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-all",
          "version": {
            "requires": "6.0_BETA"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "bytecode-fog-1.0.0.jar",
          "url": "bytecode-fog-1.0.0.jar",
          "size": 45027,
          "sha512": "4b641d5128bf00a8365812138202fe98e561d5a730a3b27c8f7126fb6998d50f8122b95386d37d0ae0dbbbc8fe283064a526fe6b2a9ad9d5c2645bd41d359b2b",
          "sha256": "f4778ab021b98dba914c0175e33cc32331d0ae5dc859df250cddef1823e8986e",
          "sha1": "c508f0c7ab06367345f0b33ed4615a8765401e44",
          "md5": "f0b87f6055ee14b9d0b93a6190367409"
        }
      ]
    }
  ]
}
