{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baimsg.chat",
    "module": "bytecode-fog",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "bytecode-fog-1.0.0.jar",
          "url": "bytecode-fog-1.0.0.jar",
          "size": 35919,
          "sha512": "c978a6117f2fee77bd982ef434d5a6f9c867b2f4d30db33eb51c5c3284b50bd7c98959a38c3924cec77fdd50cb281f045428eb56bcf7736db4522dfc31872c91",
          "sha256": "8b2b54015b3202c764164ddb801be221bcf76608b018632976a20bf971c81312",
          "sha1": "8604ecd10822e8be861c69b45bde3b17764985d1",
          "md5": "c4301f3496559fe3fd82fb2fbbea6993"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "bytecode-fog-1.0.0.jar",
          "url": "bytecode-fog-1.0.0.jar",
          "size": 35919,
          "sha512": "c978a6117f2fee77bd982ef434d5a6f9c867b2f4d30db33eb51c5c3284b50bd7c98959a38c3924cec77fdd50cb281f045428eb56bcf7736db4522dfc31872c91",
          "sha256": "8b2b54015b3202c764164ddb801be221bcf76608b018632976a20bf971c81312",
          "sha1": "8604ecd10822e8be861c69b45bde3b17764985d1",
          "md5": "c4301f3496559fe3fd82fb2fbbea6993"
        }
      ]
    }
  ]
}
