{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baimsg.chat",
    "module": "bytecode-fog",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "bytecode-fog-1.0.0.jar",
          "url": "bytecode-fog-1.0.0.jar",
          "size": 37896,
          "sha512": "7da0061b7236fa66fe55d921cdbdc3a7072e4171062aa0629fe3b90758e4744e879c15dabbad0d4145cb91fd2dbe817eb91553c8793534162514e778a823ae77",
          "sha256": "14756b4ccaaf3408bd74e8f9dc5e13f9d93915132cec580e61457ccbb12584dd",
          "sha1": "2071f234968d3e8af5a5e986cd249bca8a45f0c6",
          "md5": "cfea72f8700c63091fede7efeb7364b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "bytecode-fog-1.0.0.jar",
          "url": "bytecode-fog-1.0.0.jar",
          "size": 37896,
          "sha512": "7da0061b7236fa66fe55d921cdbdc3a7072e4171062aa0629fe3b90758e4744e879c15dabbad0d4145cb91fd2dbe817eb91553c8793534162514e778a823ae77",
          "sha256": "14756b4ccaaf3408bd74e8f9dc5e13f9d93915132cec580e61457ccbb12584dd",
          "sha1": "2071f234968d3e8af5a5e986cd249bca8a45f0c6",
          "md5": "cfea72f8700c63091fede7efeb7364b8"
        }
      ]
    }
  ]
}
